### ISSUE TITLE
SUMMARY.adoc 没翻译

### ISSUE THREAD

**Issue by JiaChen-Zeng** [red-china/red-docs#43]
我看它是作为 gitbook 左边的总目录用的

**Comment by pixcai** [comment]
SUMMARY感觉没必要翻译，都是一些专业名字，翻译了反而不知道是什么

**Comment by JiaChen-Zeng** [comment]
看其他语言都有翻译的，目录当然也要中文的。

![image](https://user-images.githubusercontent.com/3676278/35767475-d3f8bf68-0927-11e8-9b9e-a2fdef7cd1b2.png)

![image](https://user-images.githubusercontent.com/3676278/35767474-cc16fc7e-0927-11e8-8c5f-a79c54edfa5c.png)

**Comment by pixcai** [comment]
要译的话你提交一下吧
